export const accessToken =
	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Ikp1Y2EgS2lmdXJpIiwiZW1haWwiOiJqdWNhQGdtYWlsLmNvbSIsImlhdCI6MTcxOTM0MjIwMiwiZXhwIjoxNzE5NDI4NjAyLCJhdWQiOiJ1c2VyIiwiaXNzIjoibG9naW4iLCJzdWIiOiI1In0.I_FdqObB6fJRRrkYvZdEjuU44N7eiszfLYpMRraGtwA";
